import Head from "next/head";
import ResultField from "../components/ResultField";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResultField countriesData={data} />
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://restcountries.eu/rest/v2/all");
  const data = await res.json();
  if (!data) return { props: { data } };
  return { props: { data } };
}
